apiVersion: osp-director.openstack.org/v1beta2
kind: OpenStackControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
#  gitSecret: git-secret
  openStackClientImageURL: registry.redhat.io/rhosp-rhel9/openstack-tripleoclient:17.0
  openStackClientNetworks:
        - ctlplane
        - internal_api
        - external
  openStackClientStorageClass: hostpath-csi
  passwordSecret: userpassword
    #  caConfigMap: cacerts
  virtualMachineRoles:
    Controller:
      ctlplaneInterface: eth1
      roleName: Controller
      roleCount: 1
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      cores: 12
      memory: 64
      rootDisk:
        name: "my-root-disk"
        diskSize: 60
        baseImageVolumeName: openstack-base-img
        # storageClass must support RWX to be able to live migrate VMs
        storageClass: hostpath-csi
        storageAccessMode:  ReadWriteOnce
        # When using OpenShift Virtualization with OpenShift Container Platform Container Storage,
        # specify RBD block mode persistent volume claims (PVCs) when creating virtual machine disks.
        # With virtual machine disks, RBD block mode volumes are more efficient and provide better
        # performance than Ceph FS or RBD filesystem-mode PVCs.
        # To specify RBD block mode PVCs, use the 'ocs-storagecluster-ceph-rbd' storage class and
        # VolumeMode: Block.
        storageVolumeMode: Filesystem
      # optional configure additional discs to be attached to the VMs,
      # need to be configured manually inside the VMs where to be used.
      #additionalDisks:
      #  - name: datadisk
      #    diskSize: 500
      #    storageClass: host-nfs-storageclass
      #    storageAccessMode:  ReadWriteMany
      #    storageVolumeMode: Filesystem
  openStackRelease: "17.0"

