---
- name: Register Controller node
  hosts: Controller
  become: yes
  vars:
    repos:
      - rhel-9-for-x86_64-baseos-eus-rpms
      - rhel-9-for-x86_64-appstream-eus-rpms
      - rhel-9-for-x86_64-highavailability-eus-rpms
      - openstack-17-for-rhel-9-x86_64-rpms
      - fast-datapath-for-rhel-9-x86_64-rpms
  tasks:
    - name: Register system
      redhat_subscription:
        username: skalski
        password: RTU7rzr!nbz3qjq_wft
        release: 9.0
        org_id: 6963238
        pool_ids: 2c940595860349dd018616405ae65862 
      ignore_errors: true
    - name: Enable repos
      command: "subscription-manager repos --enable {{ item }}"
      with_items: "{{ repos }}"
