apiVersion: batch/v1
kind: Job
metadata:
  name: issu-pair-add-job
  namespace: tf
spec:
  ttlSecondsAfterFinished: 100
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      nodeSelector:
        contrail-issu: ""
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      restartPolicy: Never
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      enableServiceLinks: false
      containers:
      - name: issu-pair-add
        image: tungstenfabric/contrail-controller-config-api:latest
        imagePullPolicy: Never
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
          - "bash"
          - "-c"
          - |
            set -ex
            set -o pipefail
            exec &> >(stdbuf -i0 -o0 -e0 tee -a /var/log/contrail/issu-pair-add-job.log)
            source /etc/issu/issu.env
            mkdir -p /etc/contrail
            ln -s -f /etc/contrailconfigmaps/vnc_api_lib.ini.${POD_IP} /etc/contrail/vnc_api_lib.ini
            ln -s -f /etc/contrailconfigmaps/contrail-keystone-auth.conf.${POD_IP} /etc/contrail/contrail-keystone-auth.conf
            ret=0
            source /etc/issu/issu_node_pair.sh add || ret=1
            python3 -c "import sys; sys.stdout.flush(); sys.stderr.flush()"
            exit $ret
        volumeMounts:
        - mountPath: /etc/issu
          name: issu-config
        - mountPath: /etc/contrailconfigmaps
          name: config1-config-volume
        - mountPath: /etc/ssl/certs/kubernetes
          name: ca-certs
        - mountPath: /etc/certificates
          name: config1-secret-certificates
        - mountPath: /var/log/contrail
          name: issu-logs
      volumes:
      - name: issu-logs
        hostPath:
          path: /var/log/contrail/issu
          type: Directory
      - configMap:
          name: issu-configmap
        name: issu-config
      - configMap:
          name: config1-config-configmap
        name: config1-config-volume
      - configMap:
          name: csr-signer-ca
        name: ca-certs
      - name: config1-secret-certificates
        secret:
          secretName: config1-secret-certificates
