###############################################################################
# Role: ContrailIssu
###############################################################################
- name: ContrailControllerIssu
  CountDefault: 0
  tags:
    - primary
    - contrailissu
  networks:
    InternalApi:
      subnet: internal_api_subnet
    Tenant:
      subnet: tenant_subnet
  ServicesDefault:
    - OS::TripleO::Services::AuditD
    - OS::TripleO::Services::BootParams
    - OS::TripleO::Services::CACerts
    - OS::TripleO::Services::CertmongerUser
    - OS::TripleO::Services::Collectd
    - OS::TripleO::Services::Docker
    - OS::TripleO::Services::Podman
    - OS::TripleO::Services::Ec2Api
    - OS::TripleO::Services::IpaClient
    - OS::TripleO::Services::Ipsec
    - OS::TripleO::Services::Kernel
    - OS::TripleO::Services::LoginDefs
    - OS::TripleO::Services::ContainersLogrotateCrond
    - OS::TripleO::Services::Snmp
    - OS::TripleO::Services::Sshd
    - OS::TripleO::Services::Timesync
    - OS::TripleO::Services::Timezone
    - OS::TripleO::Services::TripleoPackages
    - OS::TripleO::Services::ContrailIssu
    - OS::TripleO::Services::ContrailIssuControl
    - OS::TripleO::Services::ContrailIssuScript
